//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class User : IUser
{
	public virtual object UserId
	{
		get;
		set;
	}

	public virtual object Mobile
	{
		get;
		set;
	}

	public virtual string Add(User user)
	{
		throw new System.NotImplementedException();
	}

}

